services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - HOSTNAME=0.0.0.0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bookshelf
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookshelf
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
